### PR TITLE
Remove extraneous text in dummies doc page

### PR DESCRIPTION
**Pull request by thomaslevesque**
I used the Github UI to make this change, and it looks like it created the branch on this repo instead of my fork... sorry about that.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
We could probably improve this page by not mentioning `Activator.CreateInstance`. Not every developer is familiar with this method, so explaining something by saying it uses `Activator.CreateInstance` might not be meaningful to everyone.

For instance:

> If T is a value type, the Dummy will be a T created via Activator.CreateInstance

could be rewritten like this:

> If T is a value type, the Dummy will be the default value for that type

And 

> If the Dummies can be found, use Activator.CreateInstance to create the Dummy, supplying the Dummies as the argument list.

could be:

> If the Dummies can be found, create an instance by calling the constructor with these dummies as arguments

**Comment by blairconrad** [comment]
> I used the Github UI to make this change, and it looks like it created the branch on this repo instead of my fork... sorry about that.

Ah, yes. That's a thing it does if you have commit rights. Whatcha gonna do?

**Review by blairconrad — APPROVED** [review]
This is a good change. I'd happily take it as is. If you want to pile on the other suggested changes, I like that too!

**Comment by thomaslevesque** [comment]
Let's leave this PR as is. I'll create an issue for the other changes

**Comment by blairconrad** [comment]
Thanks for the change. And the merge!

**Pull request merged**
