### PR TITLE
Backport fix for #899 to 2.x

### PR DESCRIPTION
**Pull request by thomaslevesque**
Connects to #899

(I just cherry-picked the merge commit)

### CODE REVIEW

**Comment by blairconrad** [comment]
I did not know that you could cherry-pick a merge commit! I'd've cherry-picked the 3 commits. Cool.

**Comment by blairconrad** [comment]
Looks great, @thomaslevesque. Thanks!

**Comment by thomaslevesque** [comment]
> I did not know that you could cherry-pick a merge commit! I'd've cherry-picked the 3 commits. Cool.

You can; you just have to specify which parent you want with `-m`

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 2.3.2
https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.3.2

Thanks for identifying it, @thunderbird55. Look for your name in the release notes. :trophy:

**Pull request merged**
