### PR TITLE
Improve non-virtual member configuration message

### PR DESCRIPTION
**Pull request by blairconrad**
Closes #1051

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Thanks @blairconrad, nice work!

**Comment by blairconrad** [comment]
It was a group effort with @chrismatheson. Thanks for the merge.

**Comment by chrismatheson** [comment]
not sure i did a lot, but happy @blairconrad had the time to improve things :)

**Comment by blairconrad** [comment]
@chrismatheson, The count of characters that you typed that made it into the change is not how we keep score.
You saw a deficiency, thought enough to comment about it, and to attempt a solution. We appreciate every portion of that.
(And I figured we'd never hear from you again, family life having got the better of you, or I would've left the PR open for you. You're not cross?)

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).

Look for your name in the release notes, @chrismatheson. :trophy:

**Pull request merged**
