### PR TITLE
Deploy to NuGet on new tag

### LINKED ISSUE #1039: Automatic NuGet deployment when release is published
Currently, when we make a new release, we manually trigger a NuGet deployment from AppVeyor. But AppVeyor also has an option to trigger a deployment when a new tag is pushed:
https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only

This would make the release process even smoother, since publishing the release on GitHub would automatically build and deploy the packages.

Depends on #1046.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #1039.
I expect. I'm not really sure how to test this without actually merging and then tagging something.
Wanna give it a go and release a 4.0.0 alpha? :wink:

### CODE REVIEW

**Comment by thomaslevesque** [comment]
> I'm not really sure how to test this without actually merging and then tagging something.

Well, we could make a dummy repo just to test it, pushing to some other deployment provider instead of NuGet...

> Wanna give it a go and release a 4.0.0 alpha? 😉

We could do that, too.

**Comment by thomaslevesque** [comment]
If we do this, we'll need to update the release checklist. "edit draft release" should come before "tag and push"

**Comment by blairconrad** [comment]
> Well, we could make a dummy repo just to test it, pushing to some other deployment provider instead of NuGet...

But that proves not that much. I mean, it tests that the thing is hooked up, but won't give us a proper release or even check that I encrypted the API key properly. We do have this from my AppVeyor build:
https://ci.appveyor.com/project/blairconrad/fakeiteasy/build/499#L659. It shows that the config was understood, and the action was skipped _for the right reason_.

> If we do this, we'll need to update the release checklist. "edit draft release" should come before "tag and push"

Oh? I don't mind, but is there a pressing need? Just to reduce the turnaround time after the build goes to NuGet?

**Comment by thomaslevesque** [comment]
> But that proves not that much.

Well, at least it will prove that deploy is indeed triggered, and if something goes wrong, at least we don't push anything to NuGet. I'm trying it now, I'll let you know how it goes.

> Oh? I don't mind, but is there a pressing need? Just to reduce the turnaround time after the build goes to NuGet?

Just so that the release notes are up to date before we deploy

**Comment by blairconrad** [comment]
> Just so that the release notes are up to date before we deploy

Fair enough. They aren't visible at that point, but I've no problems with them being up to date before deploy. Heck. I like them to be up to date _all the time_.

So if we want to release an alpha, I guess we just tag develop, yes? No need to create a branch or merge anything. (We don't need to do this right away or anything.)

**Comment by thomaslevesque** [comment]
> They aren't visible at that point

Good point. *I* always see them, so I tend to forget other people don't... OK, so maybe there's no need to change the current checklist.

> So if we want to release an alpha, I guess we just tag develop, yes? No need to create a branch or merge anything. (We don't need to do this right away or anything.)

I think so

**Comment by blairconrad** [comment]
>  so maybe there's no need to change the current checklist.

too late!

**Comment by thomaslevesque** [comment]
Thanks @blairconrad. Now let's cross our fingers...

**Comment by blairconrad** [comment]
Pre-crossed. Thanks for the merge.

**Pull request merged**
