### PR TITLE
rename UnusedCallSpecificationAnalyzerTests to UnusedReturnValueAnalyzerTests

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by blairconrad** [comment]
I think this makes sense, but just noticed that our diagnostic messages include the phrase "Unused call specification". They read well enough, so maybe best to leave that alone?

**Comment by blairconrad** [comment]
If nothing else, the change in message could be another issue even if we wanted to pursue it.

**Comment by blairconrad** [comment]
Good eye, @adamralph.

**Comment by thomaslevesque** [comment]
Actually, the name `UnusedCallSpecificationAnalyzerTests ` was intentional. `UnusedReturnValueAnalyzer` is designed to diagnose several issues related to unused return values; "unused call specification" is just one of those issues. Since the tests only covers the "unused call specification" case, I had named it `UnusedCallSpecificationAnalyzerTests `.

**Comment by blairconrad** [comment]
OH! That makes perfect sense. I am chagrined.

**Comment by thomaslevesque** [comment]
It doesn't really matter anyway... we can always split it later if we extend `UnusedReturnValueAnalyzer` to check for other issues.

**Comment by adamralph** [comment]
For me these are more like black box tests (acceptance tests/specs) so ultimately they should be named by feature than by implementation. Given that our "unit" tests for FIE, which are named by implementation, are named FakeItEasy.Tests, it probably follows that FakeItEasy.Analyzer.Tests should also be named by implementation. However, I think we need to overhaul our test project naming generally, but we can address that in https://github.com/FakeItEasy/FakeItEasy/issues/280 (which needs updating).

**Pull request merged**
