### PR TITLE
Make A.That throw when used outside of A.CallTo

### LINKED ISSUE #559: Make A<T>.Ignored throw an exception when it is invoked
I know, that sounds crazy... but it's not ;)

`A<T>.Ignored` (or its shortcut `A<T>._`) is used in call specifications to denote that any value of this argument should be a match. If you have long type names (e.g. `IEnumerable<CustomerInvoiceDetailLine>` or something like that), it can be tempting to do this:

```
var any = A<IEnumerable<CustomerInvoiceDetailLine>>.Ignored;
A.CallTo(() => x.PrintInvoiceDetails(any))....
```

However, this doesn't work, because FIE analyzes the expression in `A.CallTo` to detect calls to `A<T>.Ignored`, and in this case the expression doesn't contain it. `A<T>.Ignored` is not meant to actually be called, only to be analyzed as part of the call specification.

This can be very confusing to many users, so I think `A<T>.Ignored` should throw an exception (with a message explaining the problem) when it is invoked. It would be better to be able to detect it at compile time, but I don't think it's possible.

(this was inspired by [this question about Moq](http://stackoverflow.com/q/33669722/98713), which has the same issue)

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #559.
Closes #611.
I just rebased #611 onto master.

### CODE REVIEW

**Comment by adamralph** [comment]
@blairconrad what's the reason for this? #611 doesn't have conflicts.

**Comment by blairconrad** [comment]
No, but it would've been a nicer commit line. I'm happy to to merge #611 instead.

**Comment by blairconrad** [comment]
I merged #611 instead. (as it turns out, @thomaslevesque rebased in the meantime)

**Comment by adamralph** [comment]
:+1:

**Comment by blairconrad** [comment]
(I'd thought @thomaslevesque was awake at the time, and I'd give him the option of hitting a button rather than rebasing and then harassing me to hit the "merge" button, thereby speeding things along so I could rebase another PR before bed. Not that there was a big rush. I just thought it would save him a little bit of menial work, which I didn't mind doing while watching mindless TV. ([Castle](https://en.wikipedia.org/wiki/Castle_(TV_series)), because I knew you were curious. The episode was better than usual, actually.)

**Comment by adamralph** [comment]
:smile: all good. (I haven't that seen that one.)

**Comment by blairconrad** [comment]
It's okay. Like many "police procedurals", most weeks the episodes are eminently skippable. But the lead, Nathan Fillion, can be hilarious, so when they do a funny/quirky episode, they're quite fun…

**Comment by adamralph** [comment]
Ah, Nathan Fillion... I loved his role in Firefly and Serenity.

**Pull request closed without merging**
