### PR TITLE
stop PR's incrementing build number

### PR DESCRIPTION
**Pull request by adamralph**
Appends a random string to the end of PR build numbers:

image

### CODE REVIEW

**Comment by blairconrad** [comment]
I don't mind the change, but why the bias against incrementing the build number?

**Comment by adamralph** [comment]
It's not a huge issue. It just struck me when I force pushed the branch for #891 several times in quick succession and 3 corresponding builds appeared. Ultimately PR's are out of our control (anyone can raise them any time) so it's kind of nice to insulate the build counter against them.

**Comment by blairconrad** [comment]
Fair enough.

**Comment by adamralph** [comment]
A nice side effect is that it that it gives an easy distinction between PR's and branch builds:

image

**Pull request merged**
