### PR TITLE
Merge hotfix 1.25 to master

### PR DESCRIPTION
**Pull request by adamralph**
Here's how I did it:

```bash
git checkout master
git checkout -b merge-hotifx
git merge hotfix/1.25
# conflicts shown
git mergetool
# fix conflicts
git commit -a -m "Merge branch 'hotfix/1.25' into merge-hotfix"
```

### CODE REVIEW

**Comment by adamralph** [comment]
The network graph looks *a little* funky, but it's compounded by the fact that we have 2 overlapping PR's to the hotfix branch:

image

**Comment by blairconrad** [comment]
I appreciate the effort you put into doing this. Here's my view of the merge:

image

However, I don't see a benefit over the original. Shall I just manually merge #445?

**Comment by adamralph** [comment]
The benefit over the original is that the dev work to fix the conflicts is built by the CI server and you just need to hit the 'big green button' to merge :relieved:.

The downside of the original is the converse: you have to do offline development work (fixing conflicts) which you then push to upstream without four eyes and without a CI build having taken place on those changes :cold_sweat:.

**Comment by blairconrad** [comment]
Sorry, yes. I do see those benefits. I meant about the pretty lines.

**Comment by adamralph** [comment]
So actually that turned out really nicely. The extra merge is just shown as a little extra loop before the merge to master:

image

**Pull request merged**
