### PR TITLE
set version to 1.25.3 for next release

### PR DESCRIPTION
**Pull request by blairconrad**
preparing for 1.25.3

### CODE REVIEW

**Comment by blairconrad** [comment]
Assuming we want to release the fix for #508 in 1.25.3.

**Comment by blairconrad** [comment]
The build fails on the build server. I can rebase on top of #513 after that's merged.

**Comment by adamralph** [comment]
A rebase would have made the history slightly prettier, but ultimately it was just an overlapping PR, so I just went ahead and merged.

**Comment by blairconrad** [comment]
I wondered if you wouldn't. Thanks!

**Pull request merged**
