### PR TITLE
Provide case study of customizing read/write property's setter

### LINKED ISSUE #1783: Document how to have a get/set property invoke a side-effect on a call to set and still persist the supplied value
From @DanielRose's [comment in #962](https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-654886104)

Possibly giving the example that he and @thomaslevesque collaborated on would be best:

```c#
A.CallToSet(() => foo.Bar).Invokes((int bar) =>
{
    A.CallTo(() => foo.Bar).Returns(bar);
    foo.BarChanged += Raise.With(foo, EventsArgs.Empty);
});
```

although maybe with some cutesy candy shoppe jargon. Or a lovesick robot.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #1783.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
@blairconrad the branch is out of date

**Comment by blairconrad** [comment]
> @blairconrad the branch is out of date

Whoops. Yeah. I forgot that I merged that contribution. Rebased.

**Comment by thomaslevesque** [comment]
Thanks @blairconrad!

**Comment by blairconrad** [comment]
Thank you!

**Pull request merged**
