### PR TITLE
Make spec classes static

### LINKED ISSUE #544: make spec members static and re-enable rule CA1822
From https://github.com/FakeItEasy/FakeItEasy/pull/542#discussion_r40284574.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #544.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Thanks, @blairconrad!

**Comment by blairconrad** [comment]
Thank you!

**Comment by thomaslevesque** [comment]
Looks like you forgot some of the specs:

- `ConfigurationSpecs`
- `CreationOptionsSpecs`
- `DummyCreationSpecs`
- `EventRaisingSpecs`

Also, re-enabling the warning was probably not such a good idea, since the same ruleset is also used in other test projects. We now have 343 occurrences of CA1822 :wink:

I'm partly to blame... the changes seemed straightforward, so my review wasn't very thorough.

**Comment by thomaslevesque** [comment]
OK, this isn't as bad as I thought... I edited my previous comment.

But we still need to keep CA1822 disabled.

**Comment by blairconrad** [comment]
@thomaslevesque 

> I'm partly to blame... the changes seemed straightforward, so my review wasn't very thorough.

Not so. I should've done a better job. It's perfectly reasonable to assume that I'd've seen any warnings that were raised.

**Pull request merged**
