### PR TITLE
Don't always use ExpressionCallMatcher to describe call constraints

### LINKED ISSUE #684: find a better way to describe a call than making an ExpressionCallMatcher
From https://github.com/FakeItEasy/FakeItEasy/pull/673/files#r60991134

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #684.

### CODE REVIEW

**Comment by blairconrad** [comment]
I'd be content to squash before merging. I just kept the static-rearranging and tidying commits separate because I figured they'd really mess with the diffs.

**Comment by thomaslevesque** [comment]
> I'd be content to squash before merging. I just kept the static-rearranging and tidying commits separate because I figured they'd really mess with the diffs.

I appreciated the separate commits, that made the review much easier. I'll let you squash before merging.

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque. Squashed and built.

**Comment by thomaslevesque** [comment]
Thanks @blairconrad !

**Pull request merged**
