### PR TITLE
Fix csproj format

### LINKED ISSUE #608: Accept that csprojs will start with BOMs and not end with newlines
From https://github.com/FakeItEasy/FakeItEasy/pull/606#issuecomment-187477612.

Whenever we modify a project file in Visual Studio, the IDE adds the UTF-8 BOM to the beginning of the file and removes the final newline in the .csproj.

Rather than check the diffs and fight with the IDE on every commit, I think we should

1. update all the .csproj files to add the BOM and remove the final newline, and
1. update the .editorconfig file with
```ini
[*.csproj]
insert_final_newline = false
charset = utf-8-bom
```

Objections?

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #608.

### CODE REVIEW

**Comment by blairconrad** [comment]
No need to merge this yet. I just wanted to push it up in case there were comments. I'll rebase after #606 is merged. (I fear #605 will take a little while).

**Comment by adamralph** [comment]
@blairconrad would you complain if I merged it now?

**Comment by blairconrad** [comment]
I'd applaud!
Sorry, I should've hooted when I pushed.

**Comment by blairconrad** [comment]
:clap:

**Pull request merged**
