### PR TITLE
Merge 5.4.1 into master

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by blairconrad** [comment]
image

BUSTED! I'll branch from master and try to merge that.

**Comment by thomaslevesque** [comment]
Ah, forgot about that... It's annoying. Means we can never merge a support branch directly into master, since it will never be up to date.

**Comment by blairconrad** [comment]
We could relax the restriction about only merging branches that are up to date. I like it, but we always knew it might cause problems. Then again, I was mostly thinking of contributors, not us!
But I didn't mind doing the extra work.

**Comment by thomaslevesque** [comment]
> We could relax the restriction about only merging branches that are up to date. I like it, but we always knew it might cause problems. Then again, I was mostly thinking of contributors, not us!
> But I didn't mind doing the extra work.

Let's keep it the restriction for now. If it becomes painful, we can always revisit

**Pull request closed without merging**
