### PR TITLE
add build.cmd as a shortcut for bundle exec rake

### PR DESCRIPTION
**Pull request by adamralph**
For convenience, also includes `bundle install`, although I'm in two minds about that. Thoughts?

### CODE REVIEW

**Comment by blairconrad** [comment]
> For convenience, also includes bundle install, although I'm in two minds about that. Thoughts?

I'm lazy. How bad is the drag when I don't need to `bundle install`, and what's the behaviour if you don't include and I need to?
If I get everything else wrapped up before you answer, I'll check.

**Comment by adamralph** [comment]
On second thoughts, it's a step too far. I'll dial it back to just wrapping `bundle exec rake` for now, which I think is good in isolation. We can consider adding further candy later.

**Comment by adamralph** [comment]
amended as discussed

**Comment by blairconrad** [comment]
Thanks for the update, @adamralph.

It's nice to have a build.cmd, as we discussed the other day when looking at the `paket` problem, IIRC correctly.

**Comment by thomaslevesque** [comment]
Usually I just run `rake`, so I didn't really feel the need for a shortcut. But maybe it doesn't do exactly what I think?

**Comment by blairconrad** [comment]
I mostly run `rake` too. I'm sure there's a reason to run the `bundle` bit, but I don't know what it is.
I think the big benefit here is that often people will check out a repo and look for the `build.cmd`.
And if you're going to provide one, why not use the "best" version of running rake?

**Comment by thomaslevesque** [comment]
Good point

**Comment by adamralph** [comment]
Running just `rake` doesn't work for me because I have multiple versions of the gems (Albacore, etc.) installed and the latest version (chosen by default) doesn't work with our Rakefile. The build server has the same problem.

**Pull request merged**
