### PR TITLE
upgrade to FluentAssertions 4.6.3

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Looking good :+1: 
Anything interesting for us in this new version?

**Comment by adamralph** [comment]
> Anything interesting for us in this new version?

I've no idea :stuck_out_tongue:

**Comment by adamralph** [comment]
It looks like FA 4.6.1 (4.6.0 didn't happen) was just a lock-step release with https://www.nuget.org/packages/FluentAssertions.Json. I.e. no actual changes to FluentAssertions itself.

4.6.2 and 4.6.3 were minor bugfixes for "Structurally comparing null-valued enums" which I'm not sure we do anywhere.

So probably, this upgrade is redundant, unless we start comparing JSON.NET objects (highly unlikely) or "Structurally comparing null-valued enums" (you're guess is as good as mine).

**Comment by blairconrad** [comment]
I don't mind the redundantness. @thomaslevesque, are you against the merge?

**Comment by thomaslevesque** [comment]
> @thomaslevesque, are you against the merge?

No, I'm fine with it. It doesn't hurt to keep up to date :wink:

**Pull request merged**
