### PR TITLE
making ArgumentConstraintTrap threadsafe

### LINKED ISSUE #476: ArgumentConstraintTrap is not threadsafe
This is one of the problems preventing us from supporting parallel test execution out of the box (#60), but may not be the only factor, so I preferred to start a new issue. It is the only concrete 

The internal `ArgumentConstraintTrap` class, used to capture argument constraints using the `That` syntax (`A<SomeClass>.That.Matches(…)`), is not threadsafe. It uses a single static variable to keep trap of the captured arguments. This can cause parallel test execution to fail, whether the `That` is used to configure a fake or to assert that certain calls were made to the fake.

I believe that replacing the static `List<IArgumentConstraint>` with a `ThreadLocal<List<IArgumentConstraint>>` will fix the problem, and preliminary testing has supported this.
Of course, testing never _proves_ anything, but I think making the field ThreadLocal is a reasonable step.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #476.

### CODE REVIEW

**Comment by blairconrad** [comment]
I agonized over the test. I don't like having multithreading in the tests, but that's the entire point of the change, and I didn't want to have nothing. Then I agonized over where to put them. In the end, I let the convenience of augmenting the existing ArgumentConstraintTrapTests push me to put the test there.
I'm happy to make any changes, of course.

**Comment by adamralph** [comment]
@blairconrad finished my review. Over to you for comment

**Comment by blairconrad** [comment]
Thanks for the comments. I really enjoyed the "test" one. (Not that I didn't the other.)

**Comment by blairconrad** [comment]
@adamralph, as you'll see, I ended up using two locks to completely lock down the order in which each thread starts and finishes recording the argument constraints.
Thanks so much for the comment.

**Comment by adamralph** [comment]
:heart: the new test, specially the comment :stuck_out_tongue:

**Comment by blairconrad** [comment]
> :heart: the new test, specially the comment :stuck_out_tongue: 

ASCII art FTW.

**Pull request merged**
