### PR TITLE
Update analyzer for calls to WithNonVoidReturnType

### LINKED ISSUE #648: Common default return value of functions with generics
I am writing unit tests for little tasks that are talking to the database. My test cases also include scenarios where a given object is not found in the database, and therefore I'd like to emulate that the queries return `null`.

Now, I managed to achieve this by using the following calls:

```c#
var _session = // database session
A.CallTo(_session).WithReturnType<Foo>().Returns(null);
A.CallTo(_session).WithReturnType<Bar>().Returns(null);
// ~10 more of these with just different types defined
```

however I was wondering if there is a way of setting this up as the default behaviour - so that all calls to `_session` with a generic parameter will return `null` by default?

I don't know if it is possible in the first place, but it would probably be a nice feature.

### PR DESCRIPTION
**Pull request by thomaslevesque**
closes #648

### CODE REVIEW

**Comment by adamralph** [comment]
Should we add a test?

**Comment by adamralph** [comment]
Would it be possible to parameterise a single test to do it for all the methods?

**Comment by thomaslevesque** [comment]
> Would it be possible to parameterise a single test to do it for all the methods?

Not really, since we have to write actual valid code that uses the method... Of course, we could pass that code as a parameter, but it would be quite ugly.

**Comment by adamralph** [comment]
I think we ought to write a test. It feels a bit icky pushing this out without any proof that it works.

We have tech debt in that some of other methods aren't covered, but we can pay that off later.

**Comment by thomaslevesque** [comment]
OK. I amended the commit to add a test.

**Comment by adamralph** [comment]
That was quick! Thanks!

**Comment by blairconrad** [comment]
:+1: Thanks!

**Comment by thomaslevesque** [comment]
> That was quick!

The magic of copy-paste-edit ;)

**Pull request merged**
