### PR TITLE
default version suffix while Castle.Core is pre-release

### PR DESCRIPTION
**Pull request by adamralph**
Connects to #531

### CODE REVIEW

**Comment by adamralph** [comment]
This was removed when we merged the two rakefiles together, but we need to preserve it while we're taking a dep on Castle.Core pre-release. Without this, a fresh clone doesn't build.

**Comment by blairconrad** [comment]
> Without this, a fresh clone doesn't build.

The freshness of the clone isn't the issue, it's the lack of `VERSION_SUFFIX` environment variable, no?

I don't mind so much the current behaviour. Everything works up 'til the packing part, and the error message is pretty clear about the problem, no?

**Comment by adamralph** [comment]
Yes, it's the lack of the variable. By saying "fresh clone" I guess I was attempting to emphasise the experience for the new comer. I.e. I clone the repo, follow the how to build instructions, and I get:

> A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Castle.Core [4.0.0-beta002, )" or update the version field in the nuspec.
> F, [2016-11-28T07:28:56.887392 #13968] FATAL -- : Exec Failed. See Build Log For Detail
> rake aborted!
> Exec Failed. See Build Log For Detail

There's nothing obvious here which says "you need to set an environment varaible named "VERSION_SUFFIX" to *some string* in order for the build to work. It's not a great contributor experience.

**Comment by thomaslevesque** [comment]
Looking good, thanks @adamralph

**Comment by blairconrad** [comment]
> Yes, it's the lack of the variable. By saying "fresh clone" I guess I was attempting to emphasise the experience for the newcomer

Ah. Of course. Thanks, @adamralph.

**Pull request merged**
