### PR TITLE
trying to fix appveyor build - MERGE IF YOU FEEL LIKE IT

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by adamralph** [comment]
This seems like the most elegant fix until appveyor sort things out on their end. Should we merge this so we can keep working in the meantime?

**Comment by thomaslevesque** [comment]
> This seems like the most elegant fix until appveyor sort things out on their end. Should we merge this so we can keep working in the meantime?

👍

**Comment by blairconrad** [comment]
Yeah, let's merge.
I updated the comment to be a little more posterity-friendly.

**Comment by blairconrad** [comment]
Another successful build! We're on a roll.

**Comment by blairconrad** [comment]
I'd merge, since we have an "approved" state, but I _did_ force push another commit. It only changed the log message, but I'd feel dirty.

**Comment by adamralph** [comment]
I felt like it 😛 

Thanks @blairconrad !

**Comment by blairconrad** [comment]
Thanks for the merge, @adamralph.
@thomaslevesque did all the sleuthing. I just swept in afterwards so I could get all the glory. Maximum glory for minimal effort!

**Pull request merged**
