### PR TITLE
Switch from Git Flow to GitHub flow

### PR DESCRIPTION
**Pull request by blairconrad**
Connects to #1487.

### CODE REVIEW

**Comment by blairconrad** [comment]
For what it's worth, prepare_release still seems to do the right thing in my own repo.

**Comment by thomaslevesque** [comment]
> I think we should also update the checklist in the release issue.

[Done](https://github.com/FakeItEasy/FakeItEasy/issues/1462). I also changed the default branch to `master` and updated the branch protection rules (copied settings from `develop`)

**Comment by thomaslevesque** [comment]
> I also changed the default branch to `master` and updated the branch protection rules (copied settings from `develop`)

Oh, wait. Should we do this *after* we fast-forward master to develop? I'll roll it back for now until we had a chance to discuss it.

**Comment by thomaslevesque** [comment]
> I also changed the default branch to `master` and updated the branch protection rules (copied settings from `develop`)

> Oh, wait. Should we do this _after_ we fast-forward master to develop? I'll roll it back for now until we had a chance to discuss it.

@blairconrad I'm not sure you saw these comments. What do you think?

**Comment by blairconrad** [comment]
Sorry. Running errands. Away from computer.
I think probably better after fast forward, but not a disaster if done
early.
No reason not to fast forward as soon as M. Ralph's PR clears. Or if he
still needs to rebase, could ask him to rebase onto master...
If you want to fast forward, by all means do.

**Pull request merged**
