### PR TITLE
add octokit to Gemfile

### PR DESCRIPTION
**Pull request by adamralph**
Word of warning: I've no idea if the latest octokit works correctly for us or whether we need a specific version. The github automation part of the rakefile has never worked for me so I can't test it.

### CODE REVIEW

**Comment by blairconrad** [comment]
Thanks for this @adamralph. 
Currently I'm getting this when I try to test your change:

```
Creating pull request...
rake aborted!
Octokit::Unauthorized: GET https://api.github.com/user: 401 - Requires authentication // See: https://developer.github.com/v3
C:/PortableApps/Documents/Source/GitHub/FakeItEasy/rakefile.rb:154:in `block in <top (required)>'
Tasks: TOP => next_version
```

It's peculiar since, as far as I can tell, I am authenticated. Will continue to investigate.

Then once this is resolved, we can address your problems with the automated steps. I don't know if you ever tried it before @thomaslevesque did, so you may be running into the same problem that he (and I) run into now: the fact that http://curl.haxx.se/ca/cacert.pem now redirects to https, making it unusable. My cached pem works great (saved at the location pointed to by `%SSL_CERT_FILE%`) ("great" in that it gets me as far as the octokit error).

The "cache the pem and add an environment variable" workaround is a little annoying though.

**Comment by adamralph** [comment]
@blairconrad I imagine this because the latest version of octokit has changed. If you run `gem list octokit` that will tell you which version you were using previously (the one prior to 3.4.0 in the list). We can then set that version explicitly in the gemfile and commit that, until we figure out how to get things working with the latest octokit.

**Comment by adamralph** [comment]
Superseded by #882

**Comment by blairconrad** [comment]
> The "cache the pem and add an environment variable" workaround is a little annoying though.

So I made #883 to talk about it.

**Pull request closed without merging**
