### PR TITLE
Change "behaviour" to "behavior" throughout docs

### PR DESCRIPTION
**Pull request by blairconrad**
Or, as I wanted to call it, "adopt bad behavior".

### CODE REVIEW

**Comment by blairconrad** [comment]
> I love the branch name 

Thanks. It's nice to have an appreciative audience.

**Comment by godrose** [comment]
Too bad ((

**Comment by blairconrad** [comment]
@godrose, I share your feelings, but given our international audience, we try to adhere to "American" spelling.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.2.0).

**Pull request merged**
