### PR TITLE
Merge hotfix 3.4.2 into develop

### PR DESCRIPTION
**Pull request by thomaslevesque**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Not sure how we should handle this conflict... merge into master first, then add a commit to revert 511b6fd before merging into develop ?
Or make a different branch, remove 511b6fd from it, and merge it into develop?

**Comment by blairconrad** [comment]
> Not sure how we should handle this conflict... merge into master first, then add a commit to revert 511b6fd before merging into develop ?
> Or make a different branch, remove 511b6fd from it, and merge it into develop?

I'm a bit of a maverick, as you know, but I'd merge by hand, resolve the conflict, and push. 😲

**Comment by blairconrad** [comment]
Alternatively, making a new branch and merging sounds okay. This is one case where I'd like a fast-forward merge, though. :-)

**Comment by thomaslevesque** [comment]
> This is one case where I'd like a fast-forward merge, though. :-)

But it *can't* be a fast-forward merge, since `hotfix-3.4.2` isn't ahead of `develop`...

**Comment by blairconrad** [comment]
If we made an extra branch off `develop`, merged manually into that, then tried to merge that branch into develop using a GitHub PR, it could be fast-forwarded, and the graph would look pretty. Like the "merge it manually and push" graph, really.

It was s silly thought, perhaps.

**Comment by thomaslevesque** [comment]
> If we made an extra branch off develop, merged manually into that, then tried to merge that branch into develop using a GitHub PR, it could be fast-forwarded, and the graph would look pretty. Like the "merge it manually and push" graph, really.

I like it. But if do it with a Github PR, it won't be a fast-forward...
Did I misunderstand something?

**Comment by blairconrad** [comment]
No, you understood perfectly. That's why it would be nice to have the fast-forward merge in GitHub this time!

**Pull request closed without merging**
