### PR TITLE
refactor: upgrade to StyleCop.MSBuild 4.7.52

### PR DESCRIPTION
**Pull request by adamralph**
Has better support for C# 6, apparently.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
> Has better support for C# 6, apparently.

Not full support, though... just tried to split [this declaration](https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs#L10) on two lines, and depending on where I split, I get either this warning:

> SA1500 : CSharp.Layout : If a statement spans multiple lines, the opening curly bracket must be placed on its own line.	

Or this one:

> SA0102 : CSharp.CsParser : A syntax error has been discovered in file D:\Docs\GitHub\FakeItEasy\src\FakeItEasy.Analyzer\DiagnosticDefinitions.cs on line 11.

So it looks like I suspect property initializers aren't properly supported yet

**Comment by thomaslevesque** [comment]
Otherwise, :+1:

**Comment by adamralph** [comment]
Indeed, I tried that and some other things in https://github.com/FakeItEasy/FakeItEasy/pull/680 and StyleCop didn't like them.

**Comment by adamralph** [comment]
Raised https://stylecop.codeplex.com/workitem/7723

**Pull request merged**
