### PR TITLE
add missing static method qualification

### PR DESCRIPTION
**Pull request by adamralph**
I missed one in #1375! 😱

### CODE REVIEW

**Comment by blairconrad** [comment]
You're awfully active lately. Sure you don't want to rejoin the owner group?

**Comment by blairconrad** [comment]
Thanks, @adamralph!

**Comment by adamralph** [comment]
> Sure you don't want to rejoin the owner group?

Could be a good idea! 😝

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.7.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.7.0).

**Pull request merged**
