### PR TITLE
Fix for issue #1709 - now targeting 5.x support 

### PR DESCRIPTION
**Pull request by asgerhallas**
The support/5.x branch does not compile for me, as I have no GetTypeInformation() method for System.Type. I guess it should be GetTypeInfo()... or am I missing something?

### CODE REVIEW

**Comment by asgerhallas** [comment]
Sorry for removing the other PR, I just needed to get my own forks master back to match yours... so I wouldn't get in trouble later.

**Comment by asgerhallas** [comment]
@thomaslevesque your last comments are included in the new PR too.

**Comment by thomaslevesque** [comment]
> The support/5.x branch does not compile for me, as I have no GetTypeInformation() method for System.Type. I guess it should be GetTypeInfo()... or am I missing something?

Oh? It compiles fine for me. What doesn't compile exactly?

The `GetTypeInformation()` method is in TypeExtensions.cs, in project FakeItEasy.Tests.TestHelpers. It exists for historical reasons to resolve an ambiguity, but it has been removed in master.

**Comment by thomaslevesque** [comment]
> Oh? It compiles fine for me.

And more importantly, on AppVeyor

**Comment by thomaslevesque** [comment]
There are a few warnings left in FakeTests.cs
https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/builds/29084877#L79

**Pull request merged**
