### PR TITLE
Deprecate FakeObjectCallExtensions.Write and .WriteToConsole

### LINKED ISSUE #1030: Deprecate FakeObjectCallExtensions.Write and .WriteToConsole
From https://github.com/FakeItEasy/FakeItEasy/pull/1029#discussion_r107910202.

They don't really seem to fit here.

Once they're deprecated, we should

- [ ] create an issue for removing them in the next major release

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1030

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Oops. Didn't realize the build had failed (shouldn't I get a notification from AppVeyor when a PR fails to build?).

**Comment by thomaslevesque** [comment]
Fixed

**Comment by thomaslevesque** [comment]
> shouldn't I get a notification from AppVeyor when a PR fails to build?

Apparently there's a setting for this:

image

**Comment by blairconrad** [comment]
Sorry @thomaslevesque. I saw the failure and also thought you'd be notified.

Good change!

**Comment by blairconrad** [comment]
I'm not a fan of dismissing reviews, but @adamralph's single comment of 9 days ago has been addressed, and the change is otherwise quite straightforward. I'm inclined to merge.
@thomaslevesque, would you prefer to rebase first?

Anyone want to talk me out of dismissing @adamralph's review?

**Comment by thomaslevesque** [comment]
> I'm not a fan of dismissing reviews, but @adamralph's single comment of 9 days ago has been addressed, and the change is otherwise quite straightforward. I'm inclined to merge.

👍 

> @thomaslevesque, would you prefer to rebase first?

Done

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by thomaslevesque** [comment]
Thanks for the merge

**Comment by adamralph** [comment]
👍 all good.

**Pull request merged**
