### PR TITLE
Restore nupkgs to artifacts/output

### PR DESCRIPTION
**Pull request by blairconrad**
Connects to #1520.

### CODE REVIEW

**Comment by blairconrad** [comment]
Currently there being placed under their project build areas and are not published to the AppVeyor feed.

**Comment by adamralph** [comment]
Oops, sorry about that.

Personally I would remove that option altogether and let the packages go to the default location. They can be swept up into artifacts on Appveyor like so: https://github.com/adamralph/bullseye/blob/5b1c3d84be5c7daf8cbddb2ee8c164d629b67947/appveyor.yml#L19

**Comment by thomaslevesque** [comment]
> Personally I would remove that option altogether and let the packages go to the default location

I think I prefer to have them all in the same place. @blairconrad, what do you think?

**Comment by blairconrad** [comment]
I prefer them in one place. They're easier for computers and humans to find. While AppVeyor can be configured to sweep them up, and so can FakeItEasy's "sweep up artifacts on build failure" script, having them all appear under `artifacts/outputs` makes another behaviour better: I only have to configure _one_ custom NuGet source directory and I can consumer all my locally-built nupkgs.

**Comment by blairconrad** [comment]
> Oops, sorry about that.

It's all good. No harm done, and all three of us failed to notice the change in behaviour.

**Comment by thomaslevesque** [comment]
Thanks @blairconrad

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).

**Pull request merged**
