### PR TITLE
Document Raise.FreeForm.With limitation and dependency

### PR DESCRIPTION
**Pull request by thomaslevesque**
Relates to #1284

### CODE REVIEW

**Comment by blairconrad** [comment]
I generally like the text that you added, but have some small concerns about the positioning (some of which are exacerbated by the way the article is already structured) and a little bit the phrasing. I had a number of thoughts when I read the new article. I'd consider addressing all of them, but perhaps not in this PR:

1. The use of the bulleted list does serve to separate the `Raise.Freeform.With` notes from the following general notes on the need for a virtual method, but I wonder if some readers won't lump the latter in under the former. Perhaps we should shift the "Just as when we're trying to…" elsewhere. But I'm not entirely sure where.
2. We have a VB.NET section (which could probably use a few more words of introduction around the code sample). Since we're now explicitly saying that `Raise.Freeform.With` is C#-only, perhaps we should introduce the a C# section as well.
3. Until (unless?) we have a new mechanism for invoking free-form delegates from VB.Net, we should probably restore the `Raise.With(Of TEventHandler )` documentation to the VB.Net section of the page.

If you disagree on any points, or agree, but think they should be done later, I'm happy to merge.
Also, I'm really attacking the article based on some pre-existing problems, so if you'd rather I made the new changes instead of dumping the work on you, I'm happy to do that too.

**Comment by thomaslevesque** [comment]
You raise (haha!) valid points, but I don't really know how to address them...

> Perhaps we should shift the "Just as when we're trying to…" elsewhere. But I'm not entirely sure where.

I'm not sure either. Maybe closer to the top.

> We have a VB.NET section (which could probably use a few more words of introduction around the code sample). Since we're now explicitly saying that Raise.Freeform.With is C#-only, perhaps we should introduce the a C# section as well.

> Until (unless?) we have a new mechanism for invoking free-form delegates from VB.Net, we should probably restore the Raise.With(Of TEventHandler ) documentation to the VB.Net section of the page.

Can we defer those decisions until we know how to address the VB.NET issue?

**Comment by blairconrad** [comment]
> You raise (haha!)

You made my morning.

> > Perhaps we should shift the "Just as when we're trying to…" elsewhere. But I'm not entirely sure where.

> I'm not sure either. Maybe closer to the top.

Probably. I think we didn't originally have the line, but added it after a user had difficulties faking an event.
We could just switch

```
Let's say - for argument's sake - that we have an interface that has an event defined:
```

for

```
Given a virtual or abstract event, or one defined on an interface: 
```

and drop the other note altogether.

**Comment by thomaslevesque** [comment]
Sounds good to me. I made the changes you suggested.

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by thomaslevesque** [comment]
Thanks for the merge!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.4.0).

**Pull request merged**
