### PR TITLE
[DO NOT MERGE] Make netstd rakefile the main one

### PR DESCRIPTION
**Pull request by blairconrad**
… I just wanna see what TeamCity does with it.

### CODE REVIEW

**Comment by blairconrad** [comment]
As I feared, we'd need to add requirements for the agent to support the .NET Core tooling. (I think I used ".NET Core" right that time.)

**Comment by adamralph** [comment]
Probably a good time to switch to AppVeyor. We can leave TC building the net40 package and use AppVeyor to build the net40+netstd package.

**Comment by blairconrad** [comment]
So. Many. Banners. On the homepage.

But yeah.

**Comment by thomaslevesque** [comment]
> Probably a good time to switch to AppVeyor.

You just made my day :smile:

However, it probably won't be that easy... I've been trying for a while to get FIE to build on AppVeyor, and haven't succeeded yet.

**Comment by blairconrad** [comment]
@thomaslevesque, what's the problem? With Vanilla FIE or the netstd stuff?

**Comment by thomaslevesque** [comment]
> @thomaslevesque, what's the problem?

Well, initially I had some ruby/rake issues. After that I had a missing file issue that I didn't understand, and I didn't really have time to investigate. I don't remember the exact details. You can see it [here](https://ci.appveyor.com/project/thomaslevesque/fakeiteasy/build/85)

> With net40-only FIE or the netstd stuff?

net40-only

**Comment by blairconrad** [comment]
It appears to be trying to run the Samples as tests:

```
System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2) in C:\projects\fakeiteasy\samples\FakeItEasy.Examples\bin\Release
```

Lemme try a thing.

[Check it!](https://ci.appveyor.com/project/blairconrad/fakeiteasy)

Try this:

image

**Comment by blairconrad** [comment]
Not bad. About half an hour from not having an AppVeyor account to having a built FIE. w00t!

**Comment by blairconrad** [comment]
Oh, and for fun, a [netstd version](https://ci.appveyor.com/project/blairconrad/fakeiteasy-hcbn9).

Should we make an AppVeyor account for FakeItEasy? That seems to be the way, no? A username/password account for the org, and then the AppVeyor account will grant powers to a GitHub org?

**Comment by blairconrad** [comment]
You may have [seen some activity on that front](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy). Ahem.

**Comment by adamralph** [comment]
> Should we make an AppVeyor account for FakeItEasy? That seems to be the way, no? A username/password Appveyor account and then we grant powers to a GitHub org?

This is the bit I hate about AppVeyor. The account model is really clunky and I can never remember the optimal way to do it.

I think you're right though, we need to create an account on AppVeyor for the org and then add @FakeItEasy/owners as admins of the account. It looks like you've already done all that.

I then have to logout and log in again, choosing the FakeItEasy account, which stops me from administering my other projects on there. Ugh.

**Comment by adamralph** [comment]
BTW - we should move all our build config into `appveyor.yml` and out of clicky clicky config in the UI.

**Comment by thomaslevesque** [comment]
> I then have to log out and log in again, choosing the FakeItEasy account, which stops me from administering my other projects on there. Ugh.

Yes, there's room for improvement in that area... Other than that, there isn't much I don't like about AppVeyor.

**Comment by blairconrad** [comment]
> BTW - we should move all our build config into `appveyor.yml` and out of clicky clicky config in the UI.

Of course.

**Pull request closed without merging**
