### PR TITLE
Use MSBuild v12 if no MSBuild v14

### LINKED ISSUE #537: support build on MSBuild v14-only machines?
Per https://github.com/FakeItEasy/FakeItEasy/pull/536#issuecomment-141205040.
As a convenience to contributors, should the rakefile fall back to MSBuild version 14 when there's no version 12?

In theory the newer tools should be able to build the older projects just fine, no?

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #537.

### CODE REVIEW

**Comment by adamralph** [comment]
Isn't it the other way round? Use MSBuild v12 if no MSBuild v14?

**Comment by blairconrad** [comment]
Oh, drat. I had it that way and reversed in the rakefile after your commit, but used --no-edit with --amend. Will fix.

**Comment by adamralph** [comment]
@blairconrad the code change looks fine (if I understand it correctly), only the commit message and PR title look wrong.

**Comment by blairconrad** [comment]
Fixed, I think. Thanks!

**Pull request merged**
