### PR TITLE
Test under netcoreapp2.1

### LINKED ISSUE #1361: Run tests under .NET Core 2.1
We currently run tests under .NET Framework 4.6.1 and .NET Core 1.0.
Sometimes newer platforms introduce changes in behaviour, as noted in #1345. Even though that one bug was resolved, we should test under the newer .NET Core to ensure that everything else works (and continues to work).

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #1361

### CODE REVIEW

**Comment by blairconrad** [comment]
@thomaslevesque, I added the framework, rather than replacing netcoreapp1.0, since I think there's still value in testing against netcoreapp1.0, but I'm happy to hear dissenting opinions, as I know this will increase build times.

**Comment by thomaslevesque** [comment]
> @thomaslevesque, I added the framework, rather than replacing netcoreapp1.0, since I think there's still value in testing against netcoreapp1.0, but I'm happy to hear dissenting opinions, as I know this will increase build times.

I think we should keep netcoreapp1.0.

**Comment by thomaslevesque** [comment]
Thanks @blairconrad

**Comment by blairconrad** [comment]
Thank you!

**Pull request merged**
