### PR TITLE
Refactor argument constraint tests

### PR DESCRIPTION
**Pull request by thomaslevesque**
to avoid the use of custom ReflectedMethodData attribute, because it can't be ported to .NET Core (as discussed in https://github.com/FakeItEasy/FakeItEasy/pull/617#issuecomment-227571784)

### CODE REVIEW

**Comment by blairconrad** [comment]
Things look good, @thomaslevesque. I wouldn't mind a little time to investigate another approach, though. If you don't mind.

**Comment by thomaslevesque** [comment]
> I wouldn't mind a little time to investigate another approach, though.

I expected as much. It works, but it's certainly not an ideal solution...

> If you don't mind.

Not at all :wink:

**Comment by blairconrad** [comment]
Hmm… my initial idea would work pretty easily (I think) were it not for the subtypes declaring additional methods. I'd thought to provide instances of the subtypes (although they wouldn't have to be subtypes) that would act as test contexts. Here's a sample. I just converted 2 of the leaf classes to give an idea. Probably your method is better. I made #781 just to give an idea. It's by no means complete.

**Comment by adamralph** [comment]
If the other methods we're considering prove too cumbersome, I'd be happy quite happy with this approach. It's verbose, but dead simple. KISS.

**Comment by blairconrad** [comment]
> If the other methods we're considering prove too cumbersome, I'd be quite happy with this approach. It's verbose, but dead simple. KISS.

I feel the same way. There are a few things to remember when creating a new case (because the base tests aren't abstract, we aren't reminded to override them), but probably someone will just copy an existing class anyhow, so it'll be okay. I'd just wanted to try a different tack.

**Comment by thomaslevesque** [comment]
I find @blairconrad's solution more elegant, and probably less brittle. What worries me a little is how the tests will appear: instead of each test class appearing to have its own tests, only the base class will have tests with many test cases.

**Comment by adamralph** [comment]
I find this solution simple, and the other one complex.

I'm not sure why this solution would be more brittle. Ultimately, we're
trying to save ourselves the trouble of writing each test explicitly, so I
feel like an explicit declaration of each test, internally delegating the
heavy lifting to some thing common is more natural and easier to grok.

**Comment by thomaslevesque** [comment]
> I'm not sure why this solution would be more brittle.

Well, not very brittle... it's just that we could forget to override the test methods and/or apply the attributes in the derived classes.

**Comment by blairconrad** [comment]
I've no objection to merging @thomaslevesque's solution. I just thought it would be a fun exercise to see if approaching the problem from another angle would yield something suitable and maybe with a little less ceremony in the tests, since  @adamralph's [initial comment](https://github.com/FakeItEasy/FakeItEasy/pull/617#issuecomment-227572383) mentioned the verbosity.
I had fun, and appreciate you guys holding off on the merge while I played.

**Comment by adamralph** [comment]
> we could forget to override the test methods and/or apply the attributes in the derived classes

True, but we could equally forget to write tests for certain things, or forget attributes on any other test method. These tests are really no different to other tests in that respect, it's just that we have shortcuts under the hood for implementing them.

**Comment by adamralph** [comment]
Thanks @thomaslevesque! For the changes, and for letting us persuade you that your approach is best :-D

**Pull request merged**
