### PR TITLE
Trying to fix appveyor build - DON'T MERGE

### PR DESCRIPTION
**Pull request by thomaslevesque**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
It's ugly, but it seems to work... no idea why, though. It's as if the PATH env variable was already almost at the maximum length, and adding `C:\Ruby200\bin;` made it exceed that maximum. But in that case just doing it with `set` in cmd shouldn't change anything... unless the maximum length is an AppVeyor limitation, not a system limitation.

**Comment by blairconrad** [comment]
That is peculiar, @thomaslevesque. While it'd be nice to have the `PATH` change in the `environment` section, I'd take the pragmatic way out.
Of course, now that we have only one `rakefile`, we could instead experiment with simple-targets-csx, if we're of a mind to.

**Comment by thomaslevesque** [comment]
See https://github.com/appveyor/ci/issues/1202

**Comment by thomaslevesque** [comment]
> Of course, now that we have only one rakefile, we could instead experiment with simple-targets-csx, if we're of a mind to.

In the long run, I'd love to move away from Rake. Maybe we should start to work on it.

**Comment by adamralph** [comment]
Superseded by #935

**Comment by blairconrad** [comment]
> In the long run, I'd love to move away from Rake. Maybe we should start to work on it.

Sounds good. I'd volunteer, but I'd rather focus on my Nancy/travis issue right now. Fun with vagrant!

**Comment by blairconrad** [comment]
(Not fun with vagrants. That's a whole different thing.)

**Comment by adamralph** [comment]
Obviously I'm all for simple-targets-csx 😉

**Pull request closed without merging**
