### PR TITLE
Release 4.1.0

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by blairconrad** [comment]
I do not understand why "AppVeyor was unable to build non-mergeable pull request".

**Comment by thomaslevesque** [comment]
Shouldn't the branch be named `release-4.1.0` instead of `release/4.1.0`?

**Comment by blairconrad** [comment]
I like the `/`s, but can make `-`. You think that's the problem?
I'll rename and push and restart the PR. If that's it (or either way) will make an issue for prepare_release for the next time.

**Comment by thomaslevesque** [comment]
> I like the `/`s

Me too, but I think GitFlow (and probably GitVersion) requires `-`

**Comment by blairconrad** [comment]
GitVersion claims to be okay with `/`, and it's actually `git-flow`'s default, if I read correctly. Maybe it's AppVeyor. Or maybe something else went wrong. `-` is fine, though.

**Pull request closed without merging**
