### PR TITLE
Add FakeItEasy.Sdk.Create class to FakeItEasy.dotnet

### PR DESCRIPTION
**Pull request by blairconrad**
Connects to #531. Was missed from #617.

### CODE REVIEW

**Comment by adamralph** [comment]
:+1: thanks @blairconrad. We should really get an approval test up and running for the netstd project ASAP, since then we can do an initial baseline comparison of the approved API for the net40 and netstd projects.

**Comment by blairconrad** [comment]
> We should really get an approval test up and running for the netstd project ASAP, since then we can do an initial baseline comparison of the approved API for the net40 and netstd projects.

Agreed. If only ApprovalTests and PublicApiGenerator supported .NET Standard. :frown;

**Comment by adamralph** [comment]
@JakeGinnivan has anything been done yet towards supporting a .NET Standard in PublicApiGenerator?

**Comment by JakeGinnivan** [comment]
Not yet. 

I hope to have `.ShouldMatchApproved()` working on netcore soonish though. Just need to dedicate some time to it. 

ShouldMatchApproved() in shouldly is compatible with ApprovalTests mostly so it's really easy to switch. I cannot see ApprovalTests moving to netcore anytime soon.

**Comment by adamralph** [comment]
@JakeGinnivan thanks for the info. Does that mean "ShouldMatchApproved() in shouldly" is self contained? Or do we still need PublicApiGenerator to actually generate the files?

**Pull request merged**
