### PR TITLE
Remove ClickOnce bootstrapper from all projects

### LINKED ISSUE #688: Remove unnecessary BootstrapperPackage and ClickOnce properties from all projects
While looking for remains of .NET 3.5 support, I noticed that almost all projects in the solution have BootstrapperPackage elements:

```
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
```

I'm pretty sure they're not necessary and can be removed. Obviously, .NET 3.5 will no longer be necessary after #687 is merged, and there was no bootstrapper for .NET 4.0, which never caused any issue. As for Windows Installer, it's certainly not necessary for FakeItEasy...

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #688

### CODE REVIEW

**Comment by blairconrad** [comment]
Sometimes you remove `UpgradeBackupLocation` and sometimes not…

**Comment by thomaslevesque** [comment]
> Sometimes you remove UpgradeBackupLocation and sometimes not…

Oops! It won't do any harm, but it's not what I intended. I'll fix it.

**Comment by thomaslevesque** [comment]
Fixed (amended the commit)

**Comment by adamralph** [comment]
:+1: really glad this cruft has gone. It always irritated me.

**Pull request merged**
