### PR TITLE
Add CollectionOfDummy. Issue #675.

### LINKED ISSUE #675: Helper method for list of dummies
I really like the `Dummy` feature of FakeItEasy. One thing that I find myself needing to do on every project is to create a collection of dummies (e.g. for seeding a test database).

I always end up writing an extension method that give me a fluent syntax for this, like:
```cs
IEnumerable<User> users = 42.Dummy<User>();
```
the code for which is just something like:
```cs
public static class DummyHelpers
{
    public static IEnumerable<T> Dummy<T>(this int count)
    {
        for (var i = 0; i < count; i++)
        {
            yield return A.Dummy<T>();
        }
    }
}
```

Would you consider adding something like this to the framework? If so I would be happy to write up a pull request with any necessary tests.

---

- [x] implement - ~~#702~~
- [x] approve API change - ~~#705~~
- [ ] update docs - #710
- [x] update https://github.com/FakeItEasy/FakeItEasy/wiki/Changes-in-version-2.0

### PR DESCRIPTION
**Pull request by t0mburton**
fixes #675

### CODE REVIEW

**Comment by adamralph** [comment]
Thanks @t0mburton! The change set looks spot-on :ok_hand: 

@FakeItEasy/owners this PR LGTM. Any objection to taking this straight to RTM and bypassing 2.0.0-rc? The only public API change is the addition of `A.IList<T> CollectionOfDummy<T>(int numberOfDummies)`.

In fact, it would be interesting to merge #703 first and use this as a pilot for our API approval test.

**Comment by thomaslevesque** [comment]
Looks good to me too :+1:
Thanks @t0mburton!

**Comment by thomaslevesque** [comment]
> @FakeItEasy/owners this PR LGTM. Any objection to taking this straight to RTM and bypassing 2.0.0-rc? The only public API change is the addition of A.IList<T> CollectionOfDummy<T>(int numberOfDummies).

No objection from me

> In fact, it would be interesting to merge #703 first and use this as a pilot for our API approval test.

Good idea :+1:

**Comment by adamralph** [comment]
Thanks again @t0mburton! This will be in the 2.0.0 release. Look out for your name in the release notes! :trophy:

**Pull request merged**
