### PR TITLE
Add missing parenthesis

### PR DESCRIPTION
**Pull request by blairconrad**
Extends #749.

### CODE REVIEW

**Comment by blairconrad** [comment]
All due to @adamralph's [comment](https://github.com/FakeItEasy/FakeItEasy/pull/749/files/11c8bf0059b82e2ba8ea8cd065ba63cb9d29128d#r66037319).

**Comment by thomaslevesque** [comment]
Smallest PR ever :laughing: 

LGTM, thanks @blairconrad!

**Comment by adamralph** [comment]
No PR is too small!!! :smile:

**Comment by blairconrad** [comment]
Thanks!

**Pull request merged**
