### PR TITLE
refactor: move AssemblyInfo.cs to FakeItEasy folder to match all other cs files

### PR DESCRIPTION
**Pull request by adamralph**
It suddenly struck me that FakeItEasy.Net35 links all of its source from FakeItEasy (apart from the shims) so `AssemblyInfo.cs` is no different.

It also implies the original `CommonAssemblyInfo.cs` should also have always been `AssemblyInfo.cs` sitting inside the `FakeItEasy\Properties` folder and it's only since the analyzer that we've actually had a need for a `CommonAssemblyInfo.cs`.

The thing that highlighted this to me was when I browsed to the `src` folder and saw `CommonAssemblyInfo.cs` and `AssemblyInfo.cs` sitting next to each other, with another `AssemblyInfo.cs` sitting lower down inside `FakeItEasy.Analyzer\Properties`.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
LGTM :+1: 

Now that we're officially using VS2015, perhaps we should consider switching to a shared project. It would make it much easier to share code between FakeItEasy and FakeItEasy.Net35. Currently it's quite tedious; every time we add or move a file in a project, we have to do it again in the other.

**Comment by blairconrad** [comment]
I'd interested in a shared project as well, especially since it'd help us target 4.5 for #361 (and perhaps other reasons). Would the shared project also work for .NET Core?

**Comment by thomaslevesque** [comment]
> Would the shared project also work for .NET Core?

No, .NET Core uses yet another project model (project.json)

**Comment by thomaslevesque** [comment]
> No, .NET Core uses yet another project model (project.json)

But I *think* it would be possible to target all frameworks with the `project.json` model

**Comment by blairconrad** [comment]
> But I *think* it would be possible to target all frameworks with the `project.json` model

I thought that might be the case. Perhaps this can help with our "sharing" problem.

**Comment by adamralph** [comment]
I'm fairly sure project.json won't let us target .NET 3.5. I think it's
4.5.1 and later.  It's also a continually changing space. I'm reluctant to
do much in 'the new world' before RC2 (and even then who knows what
surprises RTM is going to bring).
On 16 Apr 2016 4:16 am, "Blair Conrad" <notifications@github.com> wrote:

But I *think* it would be possible to target all frameworks with the
project.json model

I thought that might be the case. Perhaps this can help with our "sharing"
problem.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/FakeItEasy/FakeItEasy/pull/669#issuecomment-210715729>

**Comment by thomaslevesque** [comment]
> I'm fairly sure project.json won't let us target .NET 3.5. I think it's 4.5.1 and later.

Ah, yes, forgot about that

> It's also a continually changing space. I'm reluctant to do much in 'the new world' before RC2 (and even then who knows what surprises RTM is going to bring).

Agreed

**Pull request merged**
