### PR TITLE
Use new nuget API key and better server URL

### PR DESCRIPTION
**Pull request by blairconrad**
Supports #1171.

### CODE REVIEW

**Comment by blairconrad** [comment]
I though maybe the transfer of the API key from the deploy area to an environment variable had invalidated it somehow, so regenerated one. That still failed.
Then Iooked up the push API and saw that there was a better preferred Source setting. So I deployed used it and then deployed https://www.nuget.org/packages/FakeItEasy.Analyzer.VisualBasic/4.1.0-alpha003 from my home machine. It's now delisted.

I _really_ hope this is the last time. Sorry for the churn.

**Comment by blairconrad** [comment]
In retrospect, once we decided it was okay to create an unpublicized release, I should have just run the darn script at home until it worked and then submitted a PR. Ah well. Next time.

**Comment by blairconrad** [comment]
Huzzah. Thanks for putting up with my incompetence!
https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/396#L683

**Comment by thomaslevesque** [comment]
Well done @blairconrad! Now releasing will be easier than ever.

**Comment by thomaslevesque** [comment]
I'm worried about one thing, though; in the previous builds, the deployment script had several errors, but the build was still considered successful. It looks like the errors don't make the script fail, they're just ignored.

**Comment by blairconrad** [comment]
I'm not so sure about "well done", but thanks.
I've updated the instructions in #1170.
At some point, if we become confident in the workflow, we could have the deployment also publish the GitHub release, but for now I don't mind running eyeballs over it one last time.

**Comment by thomaslevesque** [comment]
> I'm not so sure about "well done", but thanks.

Well, you made it work 😉 

> At some point, if we become confident in the workflow, we could have the deployment also publish the GitHub release, but for now I don't mind running eyeballs over it one last time.

Agreed.

**Comment by blairconrad** [comment]
> in the previous builds, the deployment script had several errors, but the build was still considered successful.

A good point. We can try to add robustification.
It was in my head as well. I expect we'll catch any failures due to lack of nuget packages (and the e-mails that we get with that) and also because we close the release ourselves, but there's no reason not to have the computer help us.

Simulating the various failures and catching them may be tricky, but we can take a stab. I've made #1183.

**Pull request merged**
