### PR TITLE
Remove NextCall

### LINKED ISSUE #642: Remove NextCall.To()
Only known uses are

* "Specifying a call by example" - http://fakeiteasy.readthedocs.org/en/stable/specifying-a-call-to-configure/#specifying-a-call-by-example
* a way to configure property setters, which will be made redundant by #175
* VB.NET syntactic sugar http://fakeiteasy.readthedocs.org/en/stable/assertion/#vbnet - an edge case feature not worth supporting

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #642.

If you prefer to wait until #175 is merged fixed, I completely understand.

### CODE REVIEW

**Comment by blairconrad** [comment]
Also, I gotta say, I _loved_ being able to change the docs at the same time.

**Comment by blairconrad** [comment]
> Also, I gotta say, I _loved_ being able to change the docs at the same time.

… if only the release notes were in the source too. Le sigh. :grinning:

**Comment by thomaslevesque** [comment]
I think you can also remove the following classes:
- `RecordingCallBuilder`
- `RecordingCallRule`
- `RecordedCallRule`

They exist only to support `NextCall.To`, as far as I can tell.

**Comment by blairconrad** [comment]
Oh, for the love of Pete, @thomaslevesque. You're absolutely right.
Last night I was thinking about what could go with `NextCall`, and I _completely_ forgot to do anything about it this morning.
So glad you're here.

**Comment by thomaslevesque** [comment]
> If you prefer to wait until #175 is merged fixed, I completely understand.

I see no reason to wait. It will make it easier to implement #637

**Comment by blairconrad** [comment]
I see no reason to wait either. I just didn't want to be difficult.

**Comment by blairconrad** [comment]
Anybody see a need to keep `FakeManager.DoNotRecordCall` and `IgnoreCallInRecording`? They're public, but probably were only ever used by `RecordingCallRule`.

**Comment by thomaslevesque** [comment]
> Anybody see a need to keep FakeManager.DoNotRecordCall and IgnoreCallInRecording? They're public, but probably were only ever used by RecordingCallRule.

I'm :+1: for removing them

**Comment by adamralph** [comment]
:fire: 'em

**Comment by blairconrad** [comment]
Don't merge! I haven't removed `DoNotRecordCall` yet.
Also, once that's gone, `IInterceptedFakeObjectCall` is no longer pulling any weight. Not sure if it's worth keeping in order to distinguish it from parent `IWritableFakeObjectCall`. How far do we want to take this? The name `IInterceptedFakeObjectCall` is a nice, intention-revealing one.

**Comment by blairconrad** [comment]
I removed `DoNotRecordCall` in a separate commit, in case we decide not to bother. Ditto `IWritableFakeObjectCall`, which was no different from `IInterceptedFakeObjectCall` once `DoNotRecordCall` was removed.
If you'd rather see another approach, or a squash, I'm more than happy to change anything.

**Comment by thomaslevesque** [comment]
> Ditto IWritableFakeObjectCall, which was no different from IInterceptedFakeObjectCall once DoNotRecordCall was removed.

:+1:

**Comment by adamralph** [comment]
@blairconrad if you're all done now, I'd vote for squashing the last 3 "remove" commits.

**Comment by blairconrad** [comment]
Oh, I probably should've commented. Squashed. Thanks!

**Comment by blairconrad** [comment]
Thanks for the merge, @thomaslevesque. And for doing my work in spotting the extra classes that could be removed!

**Comment by blairconrad** [comment]
@jeremymeng, thanks for picking up on the leftover files. And @adamralph for cleaning up.

**Pull request merged**
