### PR TITLE
swap mspec for xbehave and run the specs

### LINKED ISSUE #458: Switch from MSpec to xbehave
I've lately been preferring to write comprehensive end-to-end tests (our "specs" or acceptance tests) to unit or integration (component) tests whenever it's feasible.
To this day, every time I do something more complicated than add a single test case, I have to look up the MSpec syntax and/or copy an existing spec.
I also found it difficult and cumbersome to reuse anything other than the test setups.

Perhaps we could adopt another framework? One option would be [xbehave.net](http://xbehave.github.io/). The first time I used it, I found the test pattern easy to understand and apply.
In addition, being based on XUnit, one can leverage the lifecycle and reuse patterns in that framework, and use any testrunners that work for XUnit.

Thoughts? Objections?

### PR DESCRIPTION
**Pull request by blairconrad**
closes #458 
closes #528
closes #542

### CODE REVIEW

**Comment by blairconrad** [comment]
Bah. That didn't go so well. Not sure why.

**Comment by adamralph** [comment]
I'd like to propose a slightly different take on this. The first commit, given that it didn't include the switching of the running of the tests from mspec to xbehave is actually invalid. I'd rather amend it so that it's valid in isolation, with the following commits actually just being refactoring. In that case I'd force push, updating #542

**Comment by blairconrad** [comment]
quoth @adamralph:

>  I'd rather amend it so that it's valid in isolation, with the following commits actually just being refactoring. In that case I'd force push, updating #542

Love it. I would be thrilled to have this PR go away. Not only because it doesn't work.
Does this mean you want to do the squashing and whatnot? I'm not about who does it.
If it helps, grab my rakefile. Maybe it needs concurrency set (and a log path?).

**Comment by adamralph** [comment]
I'm on it. Expect an update soon. BTW - the build failed because the xunit console runner isn't installed as a package.

**Comment by blairconrad** [comment]
Oh? That's... odd. Make sense. But why do I have it at home !?

Jut as well, I was stopping by to make sure we'd removed MSpec from the packages.config.

**Comment by adamralph** [comment]
Are you 100% sure you ran `rake` at home? With a runner inside VS it would just work, but it would definitely need xunit.runner.console installed in the solution for rake to work.

**Comment by blairconrad** [comment]
#542 sorted itself out. Abandoning PR.

**Comment by blairconrad** [comment]
Completely rakey.
Maybe a while back I added the packages as an experiment and they're hanging out now?
I'll check my packages dir when I get home. Sometime.

**Comment by blairconrad** [comment]
I am not a packages cleaner-upper:

image

I think at least one of those Castle.Cores didn't even actually exist. At least nowhere but on my machine.

**Comment by adamralph** [comment]
Aha! Mystery solved. :smile:

The occasional `git clean -fxd` is a good thing. :wink:

**Pull request closed without merging**
