### PR TITLE
Incorrect spelling of "were" in ordered call assertion failures

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
I'm probably the one to blame for this... it's a mistake I make quite often :wink:

LGTM :+1:

**Comment by thomaslevesque** [comment]
I'll merge as soon as the build completes (GitLab has a nice "Merge when build succeeds" button, it would be nice to have it on GitHub too)

**Comment by blairconrad** [comment]
Ha! Beat you to it, @thomaslevesque!

**Comment by blairconrad** [comment]
Nice job, @adamralph.

**Comment by adamralph** [comment]
Done :-)

**Comment by blairconrad** [comment]
Thanks!

**Comment by thomaslevesque** [comment]
Released in [2.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.2.0), thanks for the fix @adamralph!

**Pull request merged**
