### PR TITLE
merge Hotfix/1.25 to master

### PR DESCRIPTION
**Pull request by adamralph**
re #442

### CODE REVIEW

**Comment by adamralph** [comment]
It wil have to be manual because of the conflicting version change.

**Comment by blairconrad** [comment]
@adamralph, I have merged in my local repo by checking out the branch into master and creating a new commit.
Then I reverted the version number changes and resolved the (dead simple) conflict in FakeItEasy.Specs.csproj.

As much as it pains me, it looks like this:

image

I can push. 

On the other hand, could we not have just merged 440-disposable? It makes a cleaner graph and we don't have to undo the version change…

image

(pretend "t" is master)

Happy to conform. Just curious.

**Comment by adamralph** [comment]
I would prefer the history to show a merge from the patch branch to master as it's the simplest way for the history to convey that patches have made back into the mainline branch. Otherwise you have to manually match up what went into the patch branch and what went into the master branch each time you want to browse that part of the history. The way we do this at work is that manual merges (if any are required) are done by a pair to satisfy the four eyes rule, but I guess that doesn't really carry over so well to the OSS world.

An alternative would be to create a new branch on master, merge the hotfix into it, correcting any conflicts, and then send a PR from that new branch into master. I guess that would satisfy all requirements of our workflow but I wonder if it's over complication? I guess it could be worth a try to see how it looks. Not that I envisage us having to do this kind of thing too much in the future. Or at least hopefully not :wink:.

**Comment by blairconrad** [comment]
So at your day job, you do the "change the version number/change it back" dance?
If it works for you, I defer to your experience. (In Subversion, we've got a whole other headache around merging fixes.)
If you've no objection to how my first screenshot looks, I'm content to push.

For your suggested alternative, would we merge just my two commits (005807b806674c2f1992d324f83955b7be75e822 and fe39e93fd5768d572bef52bba5798655c5cbdab7) to the branch off master, or did you mean merge the whole patch branch? I think the latter would look like my first screenshot, only with more lines.

**Comment by adamralph** [comment]
I would merge the whole match branch. Sec, I'll prepare an alternate PR to see how that looks.

**Comment by adamralph** [comment]
Alternate PR: https://github.com/FakeItEasy/FakeItEasy/pull/446

**Pull request merged**
