### PR TITLE
585 ihideobjectmembers namespace

### LINKED ISSUE #585: Move IHideObjectMembers to top level namespace
It's currently in `FakeItEasy.Configuration` because, I can only guess, it was originally only used for types in that namespace. We're already using it for several types not in that namespace, e.g. `IFakeOptions`. It should be in the namespace `FakeItEasy`.

### PR DESCRIPTION
**Pull request by adamralph**
fixes #585

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Everything seems to be in order. Thanks @adamralph!

**Comment by blairconrad** [comment]
We're a fan of fully-qualified namespaces, then? I'll keep an eye out.

**Comment by blairconrad** [comment]
Bah. I was hoping ReSharper would help me out here, but the setting "Redundant name qualifier" doesn't just apply to namespaces.

**Comment by thomaslevesque** [comment]
Yes, I have the same problem... it always wants so simplify `FakeItEasy.Something` into just `Something`. I don't know if there's a way to change that behavior.

**Comment by thomaslevesque** [comment]
ah, found it: _ReSharper > Options > Code Editing > C# > Code Style > Reference qualification > Prefer fully qualified name at nested scope_

**Comment by blairconrad** [comment]
Toggled. Thanks @thomaslevesque

**Pull request merged**
