### PR TITLE
upgrade to Castle.Core 3.3.3

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
LGTM, thanks @adamralph!

**Comment by adamralph** [comment]
First feature ready to go for 2.1.0!

**Comment by blairconrad** [comment]
Do we have an actual issue reported against the lack of 3.3.0?
Or expectation of user-noticeable change in behaviour?

**Comment by blairconrad** [comment]
I'm all for the upgrade, but from Core's [changes.txt](https://github.com/castleproject/Core/blob/5d7e3fce57fd6c76227996e942313be2498063a2/Changes.txt):

```
3.3.3
==================
- fixed #70 - Serilog integration modifies LoggerConfiguration.MinimumLevel
- fixed #69 - Added SourceContext to the Serilog Logger - contributed by @KevivL

3.3.2
==================
- fixed #66 - SerilogLogger implementation bug where exceptions were passed through incorrectly

3.3.1
==================
- implemented #61 - Added support for Serilog - contributed by Russell J Baker (@ruba1987)
```

I'm not sure this is a "feature"…

**Comment by adamralph** [comment]
> Do we have an actual issue reported against the lack of 3.3.0?
> Or expectation of user-noticeable change in behaviour?

Nope, I just saw the upgrade available so went ahead and did it. We've done the same for Castle.Core in the past. Of course, if there were some user issue dependent on it then we'd now put that in the 2.1.0 milestone too.

You're right about the lack of a "feature". In fact, I think 3.3.1, 3.3.2 and 3.3.3 were simply lock-step releases with https://www.nuget.org/packages/Castle.Core-Serilog/ - no changes to the Castle.Core package at all.

I'd be happy to label this as a refactoring or something else. In fact, given this new info, I probably wouldn't have raised the PR at all, but hey ho, it's in now.

I guess it does at least remove some noise from the NuGet "updates" tab, but that's already fairly polluted now with all the code analysis packages which we can't upgrade without forcing our analyzer users on to VS 2015 Update 2. :cry:

**Comment by blairconrad** [comment]
>  if there were some user issue dependent on it then we'd now put that in the 2.1.0 milestone too

I think the only thing we have is #436, which is waiting on a Castle.Core release with castleproject/Core#78 in it. I think the 4.0.0-alpha001 release has this, but I'm not tempted…

**Comment by adamralph** [comment]
No, I think we'll hold off on that one.. :smile:

**Comment by adamralph** [comment]
3.3.0 -> 3.3.3 looks like there's no change to the Castle.Core package itself so the only thing it achieves is to remove one item from the NuGet UI update tab. :feelsgood:

**Pull request merged**
