### PR TITLE
Deploy to NuGet on tag creation

### PR DESCRIPTION
**Pull request by blairconrad**
I generated a new API key just for AppVeyor. 
If I read things right, this is all we need for #1039, except to update instructions in #1015.
Of course, it's completely untested…

### CODE REVIEW

**Comment by blairconrad** [comment]
Yeah, that was apparently not it!

**Comment by thomaslevesque** [comment]
Hey @blairconrad, welcome back !

Do we need to specify the API key? It's already in the environment configuration

**Comment by blairconrad** [comment]
Thanks!

This is an excellent question, @thomaslevesque. Um. I don't know.
Then again, I prefer it in the yml to the nebulous web config.
Truth be told, I don't really understand how the deployment targets here interact with the "environments" we specify elsewhere.
The [AppVeyor deployment docs](https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only) suggest a separation between inline deployments (which we have here) and manual deployment (which we've been using). If I understand correctly.

**Comment by thomaslevesque** [comment]
> I assume this will work for pre-releases too? I.e. can we continue to set the VERSION_SUFFIX and then create the corresponding pre-release in GitHub, which will create the pre-release tag, which will trigger a build of that tag, which will trigger a push of the pre-release to NuGet?

I think so.

> Can we make it so that tags are built by AppVeyor, and then all that's needed is a single button click in the UI against that tag build to "release these artifacts"?

Yes, we can do that. But then it's basically the same thing we're already doing. 

> If so, is the removal of that manual step worth the risk?

It doesn't seem very risky to me... It will never deploy unless we publish a release. True, the manual step to deploy isn't much of a hassle, since it's already just a button click in AppVeyor, but I like the idea of doing it automatically when we publish.

> I guess that risk needs quantifying. What are the possible downsides of the automation? Is there an increased risk of releasing some bad permutation of tag and VERSION_SUFFIX?

I'm not sure what the downsides would be, as long as it only deploys when we add a tag. We might want to change how we handle `VERSION_SUFFIX`; for instance, it would be nice if it could be based on the tag.

**Comment by blairconrad** [comment]
> I'm not sure what the downsides would be, as long as it only deploys when we add a tag. We might want to change how we handle `VERSION_SUFFIX`

Indeed. The static state terrifies me.

> for instance, it would be nice if it could be based on the tag.

I think this is achievable when we have a tagged build. Not sure how easy it would be to work with when we've not yet tagged. For example, when we want to generate releases for the AppVeyor NuGet feed with a -beta001 on them.

**Comment by thomaslevesque** [comment]
> For example, when we want to generate releases for the AppVeyor NuGet feed with a -beta001 on them.

Good point. I'm not sure how we would do it.

**Comment by blairconrad** [comment]
If we're interested in reducing the risk of releasing with mismatched tag and VERSION_SUFFIX, we could use the tag name to compute the version number. If `APPVEYOR_REPO_TAG_NAME` is set, it's the version.

Of course, if it's not set, then we'd still need a way to cobble together a version. It could be the way we do it now, but it seems a little silly to keep updating a version number that's not going to be used for production builds.

**Comment by thomaslevesque** [comment]
Looks like we're still undecided on this. I suggest not to do it for now, we can always revisit later.

**Pull request closed without merging**
