### PR TITLE
Set new NuGet API key

### PR DESCRIPTION
**Pull request by thomaslevesque**

### CODE REVIEW

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.8.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.8.0).

**Comment by Mertsch** [comment]
Is this a public key? Looks like this should be a build server secret?!

**Comment by Mertsch** [comment]
@thomaslevesque Ah OK. Thanks for the info.

**Pull request merged**
