### PR TITLE
Fix analysis warning for ServiceLocatorTests

### PR DESCRIPTION
**Pull request by blairconrad**
… introduced in #659. Connects to #632.

### CODE REVIEW

**Comment by adamralph** [comment]
:+1:

**Comment by thomaslevesque** [comment]
Argh... I keep forgetting to re-run code analysis before I commit. Sorry about that, and thanks for the fix @blairconrad.

**Comment by blairconrad** [comment]
No worries. Running the Code Analysis is a pain. Slow and easy to forget…

**Comment by adamralph** [comment]
We also have a catch up task for it in each release issue, so not the end of the world if it's forgotten as we merge changes.

**Comment by blairconrad** [comment]
It's true. But I saw this one while I was checking for my one issues, and while I was around, it was no bother.

**Comment by adamralph** [comment]
Oh sure, nothing wrong with PR'ing when noticed, I did the same in #655

**Pull request merged**
