### PR TITLE
Remove word flag, which offended FxCop

### PR DESCRIPTION
**Pull request by blairconrad**
Removes a Code Analysis warning.

### CODE REVIEW

**Comment by adamralph** [comment]
:+1:

**Comment by thomaslevesque** [comment]
Which warning did FxCop give you? I ran Code Analysis before pushing the offending code, and didn't get any warning. I just tried again (on the code before your PR), and FxCop still didn't complain.

**Comment by blairconrad** [comment]
> Warning	[CA1726](http://msdn.microsoft.com/library/ms182258.aspx)	Replace the term 'flag' in member name 'AnyCallConfigurationTests.WithNonVoidReturnType_should_set_the_flag_to_apply_to_all_return_types()' with an appropriate alternate or remove it entirely.

**Comment by blairconrad** [comment]
Thanks for the merge!

**Pull request merged**
