### PR TITLE
Update docs-building dependencies

### PR DESCRIPTION
**Pull request by blairconrad**
Closes #1969.

### CODE REVIEW

**Comment by blairconrad** [comment]
I compared the contents of the docs trees incorrectly. There are differences to the produced docs. Checking with eyeballs.

**Comment by blairconrad** [comment]
Looks about the same to me.

**Comment by thomaslevesque** [comment]
So what are the differences?

**Review by thomaslevesque — APPROVED** [review]
Thanks @blairconrad!

**Comment by blairconrad** [comment]
Thank you, @thomaslevesque.

**Pull request merged**
