### PR TITLE
just pointing at website for more information

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by adamralph** [comment]
Should we explicitly link the quickstart on the website before merging this?

**Comment by blairconrad** [comment]
As a fifth button?
Or replace Docs button?
Or elsewhere?

I did wonder about losing the Quckstart link from the README, but then figured that, since the very first bulleted item in the wiki was the Quckstart, it would be fine…

image

Still, I don't mind making changes.

**Comment by adamralph** [comment]
Having thought about it a bit more, I'm finding myself taking a u-turn on this. I think it may be better to list the top level links on both. The easier we make it to find stuff the better. This is what I do for other projects, e.g. http://xbehave.github.io/ and https://github.com/xbehave/xbehave.net/blob/dev/readme.md

**Comment by blairconrad** [comment]
That's fine. I can abandon this PR. And we can put a link to the quickstart in the README.
And on the web page.
Sound good?

**Comment by adamralph** [comment]
:+1: from me

**Comment by blairconrad** [comment]
Abandoning in favour of being more verbose.

**Pull request closed without merging**
